### PR TITLE
Upgrade launcher to 1.2.0 and Felix to 7.0.3.

### PR DESCRIPTION
**Pull request by tomaszmichalak**

### CODE REVIEW

**Comment by enapps-enorman** [comment]
Updating the launcher version in the starter project is blocked until [SLING-11158](https://issues.apache.org/jira/browse/SLING-11158) is resolved

**Comment by tomaszmichalak** [comment]
OK, I checked manually and I see the error too. However, there is no error in CI - maybe there is some error in tests.

**Comment by kwin** [comment]
Felix was already updated to 7.0.3 in https://github.com/apache/sling-org-apache-sling-starter/commit/a2aba48787e0bac8e3fa333057e4c5f73523367c

**Comment by enapps-enorman** [comment]
> OK, I checked manually and I see the error too. However, there is no error in CI - maybe there is some error in tests.

Yes, the smote tests in the starter were using the feature-launcher-maven-plugin which uses an an older version of the feature-model-launcher by default.  When feature-launcher-maven-plugin is configured to use v1.1.28 or later then the SLING-11158 problem is observed.

**Comment by tomaszmichalak** [comment]
Duplicates #63

**Pull request closed without merging**
