### PR TITLE
Upgrade sling dependencies - minor bumps

### PR DESCRIPTION
**Pull request by ieugen**
Signed-off-by: Ioan Eugen Stan <ieugen@apache.org>

### CODE REVIEW

**Comment by ieugen** [comment]
There is an issue with the authentification for /system/console - it requires form baed auth and should use basic auth.

**Comment by rombert** [comment]
> There is an issue with the integration test and authentification for /system/console/bundles.

I think that's OK. If you want to force basic auth it still works, but it defaults to form-based auth for everything.

**Comment by ieugen** [comment]
There is definitly somthing wrong there: 
- basic auth works initially - in the first seconds after start
- then it does not work and I get the form
- the form auth does not work 
- I manually go to http://localhost:8080/system/sling/form/login?resource=%2F 
- I authenticate, composum works and system/console works 

I think it is a race condition or something.

**Comment by rombert** [comment]
I can't test myself now, best to leave the specific artifacts out and file a bug or write to dev@sling

**Comment by ieugen** [comment]
I've reverted the version upgrade for `webconsolesecurityprovider` provider version from 1.2.0 -> 1.0.0 . This fixed the tests. I think we have a winner :).

**Comment by rombert** [comment]
Applied, thanks for the contribution @ieugen !

**Pull request merged**
