### PR TITLE
SLING-9491 generate bnd OSGi index

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
I raised https://github.com/bndtools/bnd/issues/4125 for the error message.

**Review by rombert — COMMENTED** [review]
Thanks @kwin, this looks good to me. Can we update the configuration to include the 'local' repository as well? For instance when I'm developing against bundle that is not release or available only locally the index generation fails:

```
[ERROR] Failed to determine the artifact URI for artifact org.apache.felix:org.apache.felix.metrics.osgi.collector:jar:0.1.0-SNAPSHOT
java.io.FileNotFoundException: Unable to index artifact org.apache.felix:org.apache.felix.metrics.osgi.collector:jar:0.1.0-SNAPSHOT. The repository local is not known to this resolver
    at aQute.bnd.maven.indexer.plugin.IndexerMojo$RepositoryURLResolver.resolver (IndexerMojo.java:343)
    at aQute.bnd.maven.indexer.plugin.IndexerMojo.execute (IndexerMojo.java:177)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
```

**Comment by kwin** [comment]
Using https://github.com/bndtools/bnd/tree/master/maven/bnd-indexer-maven-plugin#the-local-index-goal does not make too much sense, as you would never use/reference such an index. WDYT about this approach: https://github.com/bndtools/bnd/tree/master/maven/bnd-indexer-maven-plugin#using-indexes-at-development-time. In addition we should enforce remote URIs also during Releases!

**Comment by rombert** [comment]
@kwin - I misunderstood the error message - I thought this was about the local Maven repository. Your proposal sounds good to me.

**Comment by kwin** [comment]
@rombert Can you check again now? it should only have an effect now on CI/release builds.

**Review by rombert — APPROVED** [review]
LGTM now, thanks

**Pull request merged**
